# Generated by Django 3.1.6 on 2021-02-01 16:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('banner', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collegename', models.TextField(default='')),
                ('video', models.URLField()),
                ('description', models.TextField()),
                ('banner', models.ImageField(upload_to='')),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('college', models.TextField()),
                ('college_location', models.TextField()),
                ('name', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('college_email', models.EmailField(max_length=254, null=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('college', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('college_email', models.EmailField(max_length=254, null=True)),
                ('request', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('college', models.TextField()),
                ('name', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('file', models.FileField(default='Null', upload_to='data')),
                ('request', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vlogger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('college', models.TextField()),
                ('facebook', models.TextField()),
                ('phone_mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('channel', models.URLField()),
                ('image', models.ImageField(upload_to='')),
                ('bio', models.TextField()),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vlogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('vlogurl', models.URLField(null=True)),
                ('banner', models.ImageField(upload_to='')),
                ('views', models.IntegerField()),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UI.college')),
                ('vlogger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UI.vlogger')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.TextField()),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('vlogurl', models.URLField(null=True)),
                ('banner', models.ImageField(upload_to='')),
                ('views', models.IntegerField()),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UI.college')),
            ],
        ),
    ]
